### ISSUE TITLE
Testnet Participants earning points > 1000 just from mining blocks

### ISSUE THREAD

**Issue by aditya-manit** [iron-fish/website-testnet#124]
I saw the leaderboard has a bug and people are earning points > 1000 just from mining block

Ideal behaviour as per my understanding is a person can earn rewards for max 10 blocks which should be 1000 points in total from mining blocks
<img width="1121" alt="Screenshot 2021-12-05 at 8 56 32 PM" src="https://user-images.githubusercontent.com/40714633/144752839-9739d4fe-9557-4557-8fa9-d4a91a055e82.png">

**Comment by bogdanteodoru** [comment]
@aditya-manit it's 1000 per week, not 1000 points ever. A new week has started and they can earn points again. This is not a bug.

**Comment by dguenther** [comment]
We should double-check this -- It's probably due to the server week rolling over to the next week, allowing additional block points to be received, but the client is fetching multiple weeks' worth of point data.

**Comment by aditya-manit** [comment]
Also I noticed leaderboard is not consistent, for example the guy in the screenshot is number 1 right now on the leaderboard. But this week only shows 4 blocks for him, is you noticed his other all time stats metrics - he has done nothing except mining - so I guess all blocks were mined in the previous week ? In that case he should have max of 1400 points. 

<img width="1032" alt="Screenshot 2021-12-08 at 10 10 48 AM" src="https://user-images.githubusercontent.com/40714633/145149299-e01de935-1131-4aa7-8df0-4de321a2d7ba.png">
<img width="1039" alt="Screenshot 2021-12-08 at 10 13 57 AM" src="https://user-images.githubusercontent.com/40714633/145149586-e37351dd-d379-44e1-a025-30803de12b5a.png">
Or maybe I think the leaderboard takes time to load ? Since his recent block are not earning him points meaning he has already mined 10 blocks in this week ? But the metric shows only 4.
<img width="949" alt="Screenshot 2021-12-08 at 10 14 53 AM" src="https://user-images.githubusercontent.com/40714633/145149657-1f4c691d-5e01-48aa-988e-187e07fe5e24.png">

**Comment by dguenther** [comment]
We verified that the server-side point counts are working as expected -- based on what you pointed out above, I'm fairly sure that the leaderboard/website page is off by one when querying points (as an example, the server may be starting a new week on Sunday, but the website may be fetching points/data for the week starting on Monday).

There's a bit of work in that direction with this PR: https://github.com/iron-fish/website-testnet/pull/127 Ideally we'd like the server to send down the dates a given week starts and ends so that we can display a countdown to end of week on the site, and also so that the website knows exactly which dates to query to fetch points for the current week. We could also add an API that only returns point totals for the currently active week.

**Comment by dguenther** [comment]
My above statement was incorrect -- the server was actually counting points with Sunday as the start of the week rather than Monday. We updated the server and recalculated points so they're now in line with the website, so the points should be correct now. Please open another issue if you see other issues with point display/calculation, thanks!
