### ISSUE TITLE
Server wrongfully starts a new week on Sundays

### ISSUE THREAD

**Issue by alxs** [iron-fish/website-testnet#132]
Mostly I'm trying to be explicit about which one should be considered correct with this.

Most of the world starts the new week on Monday which is also what the website describes https://testnet.ironfish.network/about

As suggested in the discussion of #124, the server and the website are off by one day - this leads to the leaderboard reporting too many points for participants who had already mined more than 10 blocks before Sunday and any block on Sunday, and now too few points for everyone that has mined more than 10 blocks in this week + Sunday. The reports should be from Monday to Sunday.

**Comment by dguenther** [comment]
Thanks for filing an issue! We've updated the API server to start weeks on Monday, as described on the about page, so that it now matches up with the website. We've also recalculated the points, so they should now show up correctly on the leaderboard + users page, both weekly and total. Please feel free to file another issue if you see other issues with the points!
