### ISSUE TITLE
Leaderboard information in profile

### ISSUE THREAD

**Issue by psevdokounian** [iron-fish/website-testnet#143]
"All Time Rank" does not match to "place" in "All Time Stats"
![image](https://user-images.githubusercontent.com/55825515/146333858-4a504d2a-4b9a-409c-b0ca-cc76785aa503.png)

**Comment by dguenther** [comment]
"All time rank" is not guaranteed to match the rank under "Blocks Mined", since other people could be awarded points for one of the other categories. That would change their total points, and thus their All Time Rank.

That said, we did have a bug where ranks we showed on the leaderboard and ranks we showed on the profile were different, which should be fixed now. #130 is the source issue for this.
